name = "cfnewseconomic2000"
main = "index.js"
# 🚨 ඉතා වැදගත් නිවැරදි කිරීම: compatibility_date එක නවතම දිනයකට යාවත්කාලීන කරන්න.
# මෙය Node.js Modules නිවැරදිව Resolve වීමට ඉඩ දෙයි.
compatibility_date = "2025-10-12" 

# Node.js core modules (crypto, stream, fs) සඳහා සහය දැක්වීමට.
compatibility_flags = ["nodejs_compat"]

# KV Namespace එක නිර්වචනය කිරීම

# Cron Trigger (Scheduled Event)
[triggers]
crons = ["*/10 * * * *"] 
